관리자 페이지 이용자DB조회 탭 생성
whileTrueDev/tp-mvp pull request #181
Opened 2021-01-21 07:14 UTC by jiyeon2

수정 후 다시 올립니다
관리자 페이지 이용자DB 탭 추가

서버  
users컨트롤러에 get /brief-info-list 추가 => 이용자 닉네임, 아이디, 최근방송날짜, 평균시청자 목록 응답  
broadcast-info컨트롤러에 get /:userId 추가 => userId에 해당하는 방송목록 응답

클라이언트  
pages/AdminUsers => 이용자DB탭 눌렀을 때 이용자 목록 보여주는 페이지  
pages/UserBroadcast => 이용자 목록에서 이름 눌렀을 때 해당 이용자의 방송목록 보여주는 페이지

2021-01-21 12:28 UTC, hwasurr requested changes

2021-01-21 12:28 UTC, hwasurr commented on client/admin/src/organisms/users/UserBroadcastTable.tsx
> +import DownloadButton from './DownloadButton';
이런 organisms 에서 사용되는 organisms 컴포넌트의 경우
저는 /sub 폴더를 따로 두고 더 하위에 두는 것을 선호해요

컴포넌트가 많아지면 상/하 구조가 헷갈리는 경우가 많더라구요 ㅠㅠ

많은 컴포넌트가 있는 것이 아니니 지금은 그대로 두어도 상관 없을 것 같습니다!

2021-01-21 12:28 UTC, hwasurr commented on client/admin/src/organisms/users/DownloadButton.tsx
> +  const exportFileName = '편집점';
직접 다운로드 받아보니 파일명이 모두 편집점.zip로 통일되어 불편하더라구요..

각 방송에 대한 다운로드마다  
해당 크리에이터의 이름 + 방송명 또는 날짜 를 조합한 파일명을 만들어 다운로드 시키는게 사용자 입장에서 더 편할 것 같습니다!

2021-01-21 12:28 UTC, hwasurr commented on client/admin/public/dummy.csv
> +1,2,3
사용되는 파일인가요??

2021-01-21 12:28 UTC, hwasurr commented on server/src/resources/users/users.controller.ts
> +  /**
작성하신 함수 바로 윗줄에 커서를 두고
`/** ` 를 치시고 엔터를 치시면 표준처럼 쓰이는 주석 형태가 곧바로 만들어집니다!
파라미터가 있다면 파라미터 정보도 바로바로 적을 수 있도록 생성됩니당

이 기능 활용하시면 통일된 형태의 주석을 작성하실 수 있을거에요!

2021-01-21 12:28 UTC, hwasurr commented on server/src/resources/broadcast-info/broadcast-info.controller.ts
> +  getStreamsByUserId(@Param() param: {userId: string}): Promise<BroadcastDataForDownload[]> {
```ts
getStreamsByUserId(@Param('userId') userId: string): Promise<>
```
와 같이 사용할수도 있어요!

2021-01-21 12:32 UTC, hwasurr commented on server/src/main.ts
> +    'https://admin.mytruepoint.com', 'https://test-admin.mytruepoint.com',
관리자 페이지 테스트 환경 조성을 위해 api서버 요청 화이트리스트에 추가했습니다!
확인바랍니다 @jiyeon2

2021-01-21 12:52 UTC, hwasurr commented on server/src/resources/users/users.service.ts
> +  async getAllUserBriefInfoList(): Promise<BriefInfoDataResType> {
JOIN을 활용해서 다음과 같이 수정할 수 있을 것 같아요!
방송 날짜를 기준으로 최신 순으로 정렬도 추가하구용

~~~ts
const result = await this.usersRepository.createQueryBuilder('users')
  .innerJoinAndSelect(StreamsEntity, 'streams', 'streams.userId = users.userId')
  .select([
    'users.userId AS userId',
    'users.nickName AS nickName',
    'AVG(streams.viewer) AS averageViewer',
    'MAX(streams.endDate) AS recentBroadcastDate',
  ])
  .groupBy('streams.userId')
  .orderBy('MAX(streams.endDate)', 'DESC')
  .getRawMany();

return result;
~~~

2021-01-22 00:36 UTC, jiyeon2 commented on client/admin/src/pages/UserBroadcast.tsx
> +      <Box pb={2}>
버튼이랑 테이블 사이 거리를 띄우기 위해서 사용했습니다.
Box컴포넌트는 useStyle사용하지 않고도 theme에 있는 spacing같은 함수를 사용할 수 있는거 같아서 가져다 썼습니다.

2021-01-25 04:57 UTC, hwasurr approved these changes
수고하셨습니다!

2021-01-25 05:00 UTC, merged

2021-01-25 05:00 UTC, jiyeon2 commented on client/admin/src/organisms/users/UsersTable.tsx
> +].map((col) => ({
감사합니다!

2021-01-25 05:01 UTC, jiyeon2 commented on client/admin/src/organisms/users/UsersTable.tsx
> +        title="이용자 조회"
atoms/Table 컴포넌트에 해당 옵션을 추가하였습니다. 감사합니다!

2021-01-25 05:02 UTC, jiyeon2 commented on client/admin/src/pages/UserBroadcast.tsx
> +        <Button onClick={history.goBack}>
생각을 못했던 부분인데 알려주셔서 감사합니다. 해당 버튼에 variant="contained" 적용하였고, 같은 페이지에 나타나는 다운로드 버튼과 배경색을 통일하였습니다.

2021-01-25 05:03 UTC, jiyeon2 commented on client/admin/src/organisms/users/UserBroadcastTable.tsx
> +import DownloadButton from './DownloadButton';
알려주셔서 감사합니다! 컴포넌트가 많지는 않지만  /sub 폴더를 생성해서 organism내에서 사용되는 컴포넌트를 옮겨두었습니다

2021-01-25 05:04 UTC, jiyeon2 commented on client/admin/src/organisms/users/DownloadButton.tsx
> +  const exportFileName = '편집점';
크리에이터 이름(nickname)이 없는 경우가 있어서 우선 "크리에이터id_방송명_날짜" 형태로 파일명을 변경해두었습니다

2021-01-25 05:05 UTC, jiyeon2 commented on client/admin/public/dummy.csv
> +1,2,3
사용되지 않는 파일이라 삭제하였습니다..

2021-01-25 05:05 UTC, jiyeon2 commented on server/src/resources/users/users.controller.ts
> +  /**
넵 감사합니다!!

2021-01-25 05:07 UTC, jiyeon2 commented on server/src/resources/broadcast-info/broadcast-info.controller.ts
> +  getStreamsByUserId(@Param() param: {userId: string}): Promise<BroadcastDataForDownload[]> {
Param의 키를 바로 가져올 수 있다는 걸 배웠습니다 감사합니다~~

2021-01-25 05:07 UTC, jiyeon2 commented on server/src/main.ts
> +    'https://admin.mytruepoint.com', 'https://test-admin.mytruepoint.com',
확인했습니다!

2021-01-25 05:09 UTC, jiyeon2 commented on server/src/resources/users/users.service.ts
> +  async getAllUserBriefInfoList(): Promise<BriefInfoDataResType> {
queryBuilder로 조인하는 방법을 잘 몰라서 코드를 이상하게 짜뒀는데 예시 코드까지 써주셔서 감사합니다!
수정한 코드에서는 inner join 대신 left join을 사용하여 방송목록이 없는 이용자도 목록에 나오도록 해두었습니다